server:
  port: 9001

spring:
  application:
    name: ACCOUNTS-SERVICE
  datasource:
    url: ${DATASOURCE_URL:jdbc:mysql://3.129.9.179:30036/PocketPay}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:Bootcamp@67}
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  flyway:
    baseline-on-migrate: true
    validate-on-migrate: false
    enabled: false

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: https://bc67-sr.fe-assignment.tk/eureka/
  instance:
    hostname: bc67-sr.fe-assignment.tk
