server:
  port: 8762

spring:
  application:
    name: SERVICE-REGISTRY
  datasource:
    url: ${DATASOURCE_URL:jdbc:jdbc:mysql://3.129.9.179:30036/PocketPay}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:Bootcamp@67}
  mvc:
    hiddenmethod:
      filter:
        enabled: true

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: https://bc67-sr.fe-assignment.tk/eureka/
  instance:
    hostname: bc67-sr.fe-assignment.tk
