apiVersion: v1
kind: Service
metadata: 
  name: mock-server-service
  labels:
    type: mock-server
spec:
  type: ClusterIP
  ports:
    - port: 3005
      targetPort: 3005
  selector:
    type: mock-server
